---
sudo: required

language: python

python:
  - 2.7

addons:
  apt:
    packages:
      - python-pip

git:
  depth: 1

cache:
  apt: true
  timeout: 691200

install:
  - pip install ansible

script:
  - ansible --version
