---
- name: Download Zephir.
  git:
    repo: 'https://github.com/phalcon/zephir.git'
    dest: "{{ zephir_path }}"
    version: "{{ zephir_version }}"

- name: Install Zephir
  script: "ZEPHIRDIR={{ zephir_path }} {{ zephir_path }}/install"
